SciML/Catalyst.jl

- src/DiffEqBiological.jl
- src/problem.jl
- test/REQUIRE
- test/runtests.jl
- test/steady_state.jl
Pretty self-explanatory, I made sure that we can pass a reaction network to the SteadyState solving machinery.
> Steady state overload

- src/reaction_network.jl
- test/solver_test.jl
- t now reserved for time.
- t will now be properly detected as time.
> Proper usage of the time variable, t

- src/reaction_network.jl
> - Added a 1* in jacobian entries to ensure expression type.

- src/reaction_network.jl
- test/func_test.jl
Added hillr and mmr functions so hill repressors and mm repressors can be written in easier
(e.g. v*(K^n)/(K^n+X^n))
> - Add default functions for hill and mm repressors.

- src/massaction_jump_utils.jl
Fixes [83](https://github.com/JuliaDiffEq/DiffEqBiological.jl/issues/83).
> missing jumps fix

- .gitignore
- Project.toml
and ignore Manifest.toml files in git.
> add SparseArrays dependency

- src/equilibrate_utils.jl
Remove some uses of Int64  in equilibrate_utils.
> - Remove some Int64

- README.md
Written the basic usage information for find steady states and bifurcation diagrams.
> Add basic steady state/bifurcation

- CITATION.bib
This one is kinda niche since most users probably won't use this functionality. However, we should have it somewhere for people to get if they do use it.
> Add citation for HomotopyContinuation

- src/DiffEqBiological.jl
- src/equilibrate_utils.jl
- test/equilibrate_test_4.jl
There were two functions (add_hc_template and make_hc_template) which modified their input arguments, but for which I forgot to add ! at the end. Now this is fixed.
> Add ! after function names

- Project.toml
- src/DiffEqBiological.jl
I added some missing test dependencies. I'm not sure if there's any reason to keep the dependency on Compat (saw https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/130), since tests pass without it.
> Fix test dependencies and update Project.toml

- src/plot_recipes.jl
There were some minor issues with the plot receipts for some of the more obscure plots. These should now be fixed.
> - Fixes to some minor issues with bifurcation grid plotting.

- Project.toml
- README.md
- docs/make.jl
- docs/src/index.md
- src/Catalyst.jl
- src/latexify_recipes.jl
- test/latexify.jl
- test/runtests.jl
I can't get it to work in the docs due to mhchem issues with Katex, but it works in Jupyter and at the commandline.
> add back latexify and update docs

- Project.toml
- src/graphs.jl
- src/networkapi.jl
- src/reaction_network.jl
- test/api.jl
- test/graphs.jl
- test/make_model.jl
- test/runtests.jl
Also fixed some test warnings on 1.5 due to scoping.
> Fix Usage of ModelingToolkit Accessor Functions 

- src/graphs.jl
- src/latexify_recipes.jl
Should close https://github.com/SciML/Catalyst.jl/issues/245 and close https://github.com/SciML/Catalyst.jl/issues/246.
> always check if rate is an Operation

- Project.toml
- src/graphs.jl
- src/latexify_recipes.jl
@shashi getting errors in Latexifying from this line:
https://github.com/SciML/Catalyst.jl/blob/4078eaf242ec8954183e4ebf2854a177634df8ba/src/latexify_recipes.jl#L66
giving the error:
```julia
julia> Expr(rx1)
ERROR: TypeError: in Expr, expected Symbol, got a value of type Term{Real}
Stacktrace:
[1] Expr(::Any, ::Vararg{Any,N} where N) at ./boot.jl:224
[2] top-level scope at REPL[33]:1
julia> @which Expr(rx1)
Expr(args...) in Core at boot.jl:224
julia> convert(Expr,rx1)
ERROR: MethodError: Cannot `convert` an object of type Term{Real} to an object of type Expr
Closest candidates are:
convert(::Type{Expr}, ::Revise.RelocatableExpr) at /Users/isaacsas/.julia/packages/Revise/x84rs/src/relocatable_exprs.jl:22
convert(::Type{T}, ::T) where T at essentials.jl:171
Expr(::Any...) at boot.jl:224 …
```
> fix graph plotting and Latexifying

- docs/src/tutorials/bifurcation_diagram.md
Adds a tutorial for creating bifurcation diagrams to the docs.
> Add bif tutorial

- Project.toml
- README.md
- docs/src/api/catalyst_api.md
- docs/src/index.md
- docs/src/tutorials/using_catalyst.md
- src/Catalyst.jl
- src/graphs.jl
Closes https://github.com/SciML/Catalyst.jl/issues/300
> Reenable graphs

- Project.toml
- src/Catalyst.jl
- src/graphs.jl
- test/graphs.jl
- test/runtests.jl
Seeing if I can get the jll to load for testing while keeping optional for users (since it still has an open issue on Mac OS).
> try to add back Graphviz tests

- Project.toml
- README.md
- docs/src/tutorials/basics.md
- docs/src/tutorials/generated_systems.md
- src/Catalyst.jl
- src/graphs.jl
- src/networkapi.jl
- src/reaction_network.jl
- test/custom_functions.jl
- test/higher_order_reactions.jl
- test/make_jacobian.jl
- test/make_model.jl
- test/model_modification.jl
- test/newarrows.jl
- test/plotting.jl
- test/runtests.jl
- test/solve_ODEs.jl
- test/solve_SDEs.jl
- test/solve_jumps.jl
- test/steady_state_problems.jl
- test/u0_n_parameter_inputs.jl
Also gets rid of a bunch of warnings from not using system getters.
> Add new arrows for 1.6

- test/conslaws.jl
- test/test_networks.jl
Addition to [this PR](https://github.com/SciML/Catalyst.jl/pull/337)
> Added more tests for conservation law detection

- src/latexify_recipes.jl
- test/custom_functions.jl
- test/latexify.jl
- test/make_model.jl
- test/test_networks.jl
Changes some names in test file to use new function name convention.
> change_test_stuff

- docs/src/tutorials/generating_reactions_programmatically.md
hi @isaacsas 
accomodating `collect()` function as per new `Symbolics` and `Modelingtoolkit`
closes https://github.com/SciML/Catalyst.jl/issues/350
> Updating tutorial on generating_reactions_programmatically

- .github/workflows/Documentation.yml
To try to avoid out of date registry errors, following the instructions at:
https://github.com/JuliaRegistries/General/issues/16777#issuecomment-847075527
> update doc action

- src/Catalyst.jl
- src/graphs.jl
Visualization of reaction network as a network of reaction complexes
```julia
using Catalyst
rns  = Vector{ReactionSystem}(undef,6)
rns[1] = @reaction_network begin
k₁, 2A --> B
k₂, A --> C
k₃, C --> D
k₄, B + D --> E
end k₁ k₂ k₃ k₄
GraphComplexNetwork(rns[1])
```
```julia
rns[2] = @reaction_network begin
k₁, A --> B
k₂, B + B --> C + B
k₃, B + C --> A + C
end k₁ k₂ k₃
GraphComplexNetwork(rns[2])
```
```julia
rns[3] = @reaction_network begin
k₁ , ∅ --> X₁
( k₂/(1 + X₁*X₂ + X₃*X₄ ), k₃/(1 + X₁*X₂ + X₃*X₄ )), 2X₁ + X₂ ↔ 3X₃ + X₄
k₄, X₄ --> ∅
end k₁ k₂ k₃ k₄
GraphComplexNetwork(rns[3])
```
```julia
rns[4]  = @reaction_network begin
hillr(P₃,α,K,n), ∅ --> m₁
hillr(P₁,α,K,n), ∅ --> m₂
hillr(P₂,α,K,n), ∅ --> m₃
(δ,γ), m₁ ↔ ∅
(δ,γ), m₂ ↔ ∅
(δ,γ), m₃ ↔ ∅
β, m₁ --> m₁ + P₁
β, m₂ --> m₂ + P₂
β, m₃ …
```
>  ReactionComplexesGraph using existing Graphviz code in graphs.jl

- docs/src/api/catalyst_api.md
docs for `subnetworks` and `linkagedeficiencies`
> docs for `subnetworks` and `linkagedeficiencies`

- src/networkapi.jl
> fixing spaces for docs of subnetworks and linkagedeficieny

- HISTORY.md
- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/networkapi.jl
- test/api.jl
from https://github.com/SciML/Catalyst.jl/issues/401
> on reversibility and weak reversibility of reaction networks

- README.md
This talk from JuliaCon 2018 was the first in was introduced to catalyst. I think it is nice to document this talk into a readme file.
> Update README.md for adding an old talk of diffeqbiological from JuliaCon 2018

- src/latexify_recipes.jl
- test/latexify.jl
Closes https://github.com/SciML/Catalyst.jl/issues/474
> fix empty rn Latexify bug

- Project.toml
- test/reactionsystem_components.jl
This fixes the CI failure in https://github.com/SciML/ModelingToolkit.jl/pull/1451
> More robust MTK tests

- src/reactionsystem.jl
Closes https://github.com/SciML/Catalyst.jl/issues/484
> in problems don't pass kwargs to convert

- src/reactionsystem.jl
- test/runtests.jl
- test/symbolic_stoich.jl
> Symbolic stoichiometric coefficients

- src/reaction_network.jl
- test/symbolic_stoich.jl
Closes https://github.com/SciML/Catalyst.jl/issues/490
~~Needs tests but otherwise seems to work.~~
Follows the current conventions (which we may want to revisit soon):
1. `@reaction rate, x1*A + x2*B --> x3*C` always makes `A`, `B`, and `C` species and any other symbols within `rate`, `x1`, `x2` and `x3` parameters. Interpolation seems to work too.
2. In contrast, anything not explicitly listed as a parameter in `@reaction_network` becomes a species (as we do for rate expressions currently).
I'm starting to think it would be nicer to always assume undefined symbols in a rate are parameters, and all undefined stoichiometry coefficients are also parameters as in case 1. above. Then we could allow the list at the end of `@reaction_network` to be species if a user wants to override this. …
> Parametric stoich via DSL

- docs/src/tutorials/bifurcation_diagram.md
Update the tutorial according to discussion in https://discourse.julialang.org/t/error-with-catalyst-jl-bifurcation-diagram-tutorial/79202/7
> Update Bifurcation Tutorial

- src/networkapi.jl
- src/reactionsystem.jl
- test/api.jl
- test/reactionsystem_components.jl
Closes https://github.com/SciML/Catalyst.jl/issues/533 and fixes an issue with setting default values for constraint system variables/parameters.
> Fix symbol to variable mappings

- README.md
- docs/src/index.md
adding bibtex for bioarxiv paper of Catalyst.jl 
https://www.biorxiv.org/content/10.1101/2022.07.30.502135v1
> adding bibtex for bioarxiv paper of Catalyst.jl

- docs/src/faqs.md
Wait for https://github.com/SciML/SciMLBase.jl/pull/211 and a new SciMLBase
> vars to idxs in docs

- test/network_properties.jl
- test/runtests.jl
Courtesy of @yewalenikhil65.
@yewalenikhil65 it might be good to at some point get an example where the linkage deficiencies are not all zero, but this a nice set to add to Catalyst!
> add new network tests

- docs/make.jl
- docs/src/assets/.gitignore
- docs/src/catalyst_for_new_julia_users/intro_to_catalyst.md
- docs/src/index.md
@ArnoStrouwen does this look reasonable to you? I was having issues building docs locally unless I was in a specific directory, and also noticed this was using hardcoded unix-style paths instead of `joinpath`.
> fix local doc builds, use joinpath, and tweak tutorial

- src/reaction_network.jl
- src/reactionsystem.jl
- test/make_model.jl
Basically https://github.com/SciML/Catalyst.jl/pull/598
> Fix forbidden symbols

- test/dsl/custom_functions.jl
- test/dsl/dsl_basics.jl
- test/dsl/dsl_model_construction.jl
- test/dsl/dsl_options.jl
- test/miscellaneous_tests/api.jl
- test/miscellaneous_tests/symbolic_stoichiometry.jl
- test/miscellaneous_tests/units.jl
- test/model_simulation/make_jacobian.jl
- test/model_simulation/simulate_ODEs.jl
- test/model_simulation/simulate_PDEs.jl
- test/model_simulation/simulate_SDEs.jl
- test/model_simulation/simulate_jumps.jl
- test/model_simulation/solve_steady_state_problems.jl
- test/model_simulation/u0_n_parameter_inputs.jl
- test/network_analysis/conservation_laws.jl
- test/network_analysis/network_properties.jl
- test/programmatic_model_creation/component_based_model_creation.jl
- test/programmatic_model_creation/programmatic_model_expansion.jl
- test/reactionsystem_structure/higher_order_reactions.jl
- test/reactionsystem_structure/reactionsystem.jl
- test/visualization/graphs.jl
- test/visualization/latexify.jl
- test/visualization/plotting.jl
Continuation of https://github.com/SciML/Catalyst.jl/pull/622
> Finalise test remake

- README.md
> Reorder symbols at beginning of home readme

- src/latexify_recipes.jl
Closes https://github.com/SciML/Catalyst.jl/issues/637
> mathjax mhchem workaround

- docs/src/catalyst_functionality/dsl_description.md
I found a way to set constant species in the tests - and also in an online tutorial. Thus, I think it's reasonable/useful to include it in the docs so that it becomes public and stable API.
> mention constant species

- test/test_networks.jl
https://github.com/SciML/Catalyst.jl/pull/869
> Remove @paraemter lists in test_networks.jl

- docs/src/model_simulation/simulation_structure_interfacing.md
Updates the doc for how to interface with simulation object. use new MTK interface and also a general overhaul
> Structure interfacing doc

- docs/src/steady_state_functionality/homotopy_continuation.md
Updates the docs for homotopy continuation
> HC doc update

- docs/src/catalyst_functionality/model_visualisation.md
- docs/src/model_creation/model_visualisation.md
- test/reactionsystem_core/events.jl
- test/reactionsystem_core/higher_order_reactions.jl
- test/reactionsystem_core/symbolic_stoichiometry.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/simulation_and_solving/simulate_jumps.jl
A tutorial on methods for visualising a model
> Visualisation docs

- docs/src/introduction_to_catalyst/catalyst_for_new_julia_users.md
> Intro to catalyst new juliausers update

- src/reactionsystem_conversions.jl
To initially deal with https://github.com/SciML/Catalyst.jl/issues/825
Maybe there are some advanced symbolic ways to handle this as well, will talk to Shashi whenever I meet him (which is uncertain)
> Use `0` not `0.0` in `diff_2_zero`

- docs/pages.jl
- docs/src/model_creation/compositional_modeling.md
minimum changes for this part of the docs to pass
> Proposed compositional modelling doc updates

- src/reaction.jl
- test/reactionsystem_core/reaction.jl
- test/reactionsystem_core/reactionsystem.jl
> Revert "Update `Reaction` constructor"

- docs/src/index.md
Changing DifferentialEquations to OrdinaryDiffEq
> Proposed change to index page

- docs/src/introduction_to_catalyst/introduction_to_catalyst.md
Removes DifferentialEquation dependency
> proposed intro to Catlayst changes

- docs/src/spatial_modelling/lattice_reaction_systems.md
- docs/src/spatial_modelling/lattice_simulation_plotting.md
Seems displaying animations is non-trivial, and you only see once docs are built online. Here is another try.
> update video display strategy

- src/reaction.jl
Closes https://github.com/SciML/Catalyst.jl/issues/1018
> cleanup reaction getmetadata function and fix error mesg bug

- test/compositional_modelling/component_based_model_creation.jl
This is a bug in the tests that was found by https://github.com/SciML/ModelingToolkit.jl/pull/3027
> Remove double completion

- HISTORY.md
> history.MD update

- src/Catalyst.jl
- src/reaction.jl
- test/reactionsystem_core/reaction.jl
Needs https://github.com/SciML/ModelingToolkit.jl/pull/3123 and an MTK release.
> collect_vars support

- ext/CatalystHomotopyContinuationExtension.jl
- ext/CatalystHomotopyContinuationExtension/homotopy_continuation_extension.jl
- test/extensions/homotopy_continuation.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.
> fix: handle bug in `remove_denominators`

- src/reactionsystem_serialisation/serialise_reactionsystem.jl
- test/miscellaneous_tests/reactionsystem_serialisation.jl
- test/runtests.jl
There is still an MTK issue we need fixed (https://github.com/SciML/ModelingToolkit.jl/issues/3275), but it seems like a clear bug, so have just references it and marked the corresponding test as broken.
> Fix serialisation tests

- test/reactionsystem_core/coupled_equation_crn_systems.jl
- test/upstream/mtk_problem_inputs.jl
- test/upstream/mtk_structure_indexing.jl
Went through the MTK tests, fixed some things. Unfortunatelye everything major that was broken still is.
> MTK tests update

- docs/src/spatial_modelling/lattice_reaction_systems.md
- ext/CatalystCairoMakieExtension/cairo_makie_extension_spatial_modelling.jl
some axis labels were incorrect. Also, identical file names in docs seem to have made one place display the wrong movie.
> Spatial plotting fixes

- docs/src/faqs.md
- docs/src/model_creation/chemistry_related_functionality.md
Adds an FAQ section going through the symbol inference in the DSL
> DSL inference FAQ section

- test/reactionsystem_core/coupled_equation_crn_systems.jl
- test/reactionsystem_core/reactionsystem.jl
The last ones I found when going through the files (cannot guarantee that there are not more, but didn't see any at least)
> Update missing test symbolic indexing of solutions

- docs/src/model_simulation/simulation_introduction.md
Fixes https://github.com/SciML/Catalyst.jl/issues/1313#issuecomment-3151105873
> Fix docs typo
