SciML/Catalyst.jl

- src/reactions.jl
- test/higher_order_reactions.jl
- test/runtests.jl
To my opinion is the current calculation of the reaction rate is not correct for the case of higher with order > 1. 
For example for a dimerization the current implementation would consider for the reaction: 
Reaction(k,[1,1], [(1,-2), (2,1)])
The rate 
v = k*u[1]*u[1] 
but it should be 
v = k*u[1]*(u[1]-1)
since a single monomer cannot dimerize with itself. 
The propsed changes in the code should correct this.
I am not sure if it is a nice solution but it works for me.
> Higher order reactions

- src/reaction_network.jl
Since not actually used and caused issues with some input ('E', 'I', 'e') I removed the symjac calculation.
All the code is still there so we could easily add it back in if we want to, or if in the future it is calculated elsewhere we could remove the stuff related to it all together.
> Remove SymJac calculation

- src/maketype.jl
- src/problem.jl
- src/reaction_network.jl
I think I know what I am doing, I have never really used the VariableRateJumps before. But after reading some I think I understood that those should be used when e.g. the rate depends on time.
Previously only ContantRateJumps were used (for SSA). Now it will be checked whenever a reaction has a reaction rate which depends on t. If that is the case a VariableRateJump will be used instead of a ConstantRateJump for that reaction.
If such a reaction is present (and hence a VariableRateJump) something like
```julia
prob = ODEProblem(model,u0,tspan)
jump_prob = JumpProblem(prob,Direct(),model)
sol = solve(jump_prob,Tsit5())
```
should be used, rather than:
```julia
prob = DiscreteProblem(u0,tspan)
jump_prob = JumpProblem(prob,Direct(),model)
sol = solve(jump_prob,FunctionMap())
```
(I am right …
> Added usage of VariableRateJumps in addition to ConstantRateJumps

- src/maketype.jl
- src/reaction_network.jl
added `mass_action_reaction` field to generated `reaction_network`. This field simply stores the `Vector{ReactionStruct}` generated in parsing the network, which contains additional stochiometric info.
> added mass_action_reactions field to reaction_network

- src/reaction_network.jl
The `ReactionStruct` structure now contains these fields:
```julia
substrates::Vector{ReactantStruct}
products::Vector{ReactantStruct}
rate_org::Any
rate_DE::Any
rate_SSA::Any
dependants::Vector{Symbol}
is_pure_mass_action::Bool
```
> Updated ReactionStruct Structure

- src/maketype.jl
- src/reaction_network.jl
A `RegularJump` structure is now calculated (but not yet used for any problem creation).
There is a new field in the `AbstractReactionNetwork` type, `regular_jumps` which contains a `RegularJump` which can be used for SSA.
> Regular jumps

- REQUIRE
- src/DiffEqBiological.jl
- src/problem.jl
- src/reaction_network.jl
- test/REQUIRE
- test/solver_test.jl
Overload the reaction network type with the generated deterministic function  
```julia
(f::myReactionTypeName)(du, u, p, t) = f.f(du,u,p,t)
```
This mirrors what has been done in ParameterizedFunctions.jl and allows the full reaction network object to be passed along in the problems and solutions. 
This automatically allows the plot recipe to use the variable names. Closes #18.
I also updated the DiffEqJump requirement since this was causing an issue for me when testing.
> Function overload

- REQUIRE
- src/DiffEqBiological.jl
- src/massaction_jump_utils.jl
- src/problem.jl
- test/mass_act_jump_tests.jl
- test/runtests.jl
1. Added methods to convert reactions with `is_pure_mass_action=true` to `MassActionJump`s when constructing `JumpProblems`.
2. Added some test networks to make sure the produced `MassActionJump` `JumpProblem`s give the correct answer, and don't crash when having a mixture of `ConstantRateJump`s and `MassActionJump`s.
> Added conversions of jumps to MassActionJumps in JumpProblem

- src/massaction_jump_utils.jl
- src/problem.jl
- test/mass_act_jump_tests.jl
This PR should now allow the automatic generation of dependency graphs for networks with mixes of mass action and constant rate jumps. The graph is then passed into any jump problem aggregators that require a dependency graph.
I think this is actually ready to go, but it doesn't make sense to merge until my current `DiffEqJump` PR gets merged (which adds the sorting direct method SSA and a `dep_graph` named parameter for `JumpProblem`s). I'll leave it as WIP until that gets merged.
> WIP: generate dependency graph for reaction networks

- src/reaction_network.jl
- test/make_model_test.jl
Currently declaring a reaction network like
```julia
model = @reaction_network begin
1.0, X --> Y
end
```
gives a deprecation warning for the old DSL. Eventually this should be changed to create a reaction network with some default type. This PR does just that and can be merged when we think the time is right.
> Depricate default

- src/massaction_jump_utils.jl
- test/mass_act_jump_tests.jl
Updating mass action dependency graph initialization for 1.0. Also re-enabling SortingDirect method tests (which test dependency graph generation within DiffEqBiological).
> fix vector initialization for 1.0

- REQUIRE
- src/massaction_jump_utils.jl
- src/problem.jl
This should only be merged after my DiffEqJump RSSA PR, as it relies on a function to query if SSAs need dependency maps from jumps to species (and vice-versa). It won't pass integration checks until it can use that PR.
Some SSAs I'm working on require different dependency info (namely species to dependent reaction maps). This sets up DiffEqBiological to pass the required info.
> pass SSAs species to dependent reaction maps if needed

- src/DiffEqBiological.jl
```
rn = @reaction_network rType begin
(kB, kD), X + Y ↔ XY
end kB kD
```
gives 
```
ERROR: UndefVarError: ODEFunction not defined
```
due to `DiffEqBase` not being reexported.
> add reexport of DiffEqBase

- README.md
The old README seemed a bit too focused on explaining in detail a subset of the features that the DSL provides. This is an attempt to provide a more introductory README, that also shows users a simple example of how to actually solve various problem types with the DSL, while also highlighting some of the main features of the DSL. Users interested in more detailed info can then look at the docs.
Since this is a big change I'd like to get some feedback on if it is ok with others, @ChrisRackauckas, @TorkelE.
> make README more introductory

- src/maketype.jl
- src/reaction_network.jl
Add kwargs to `addodes!` to disable the construction of the symbolic Jacobian and `SymEngine` functions. 
This would only apply for the `min_reaction_network`.
Disabling Jacobians speeds up the macro enough that within seconds the ODEs for a 1200 species, 25,000 reaction network can be constructed and returned.
> kwargs to disable generation of jacobian and symfuncs

- src/reaction_network.jl
This approximation is from Higham
https://strathprints.strath.ac.uk/13549/1/siamssa.pdf
If a value ever goes negative it's unphysical, but this can make it so you can finish the step. Then rootfinding can occur to approximate the zero. This would fix the domain errors that @TorkelE had and allow domain callbacks to work.
> abs the sqrt in the CLE

- REQUIRE
- src/DiffEqBiological.jl
- src/problem.jl
- test/discreteproblem_test.jl
- test/runtests.jl
Added an overload so that we can do:
```
dprob = DiscreteProblem(rn, u0, tspan, p)
```
This allows plots of jump simulations to actually get the species syms in the legend. For example, the repressilator as a jump process:
> add DiscreteProblem overload for reaction_networks

- src/problem.jl
DiffEqBiological was using the exact parametric constructor form, which has now changed due to the addition of DEStats. This switches to using the more general form with kwargs.
> DiscreteFunction creation fix

- src/DiffEqBiological.jl
- src/massaction_jump_utils.jl
- src/network_properties.jl
- src/problem.jl
This separates out functions that we should expose for querying network properties, and also cleans up the jump creation functions a bit to avoid redundancies (since we've pre-calculated stuff in the reaction_network now that wasn't there before).
My plan is to start adding more (exported) network query functions to `network_properties.jl` as time goes on. (Things that would be useful for exporting to other packages, creating graphs, and more generally analyzing network properties.)
> separate out network query functions

- src/reaction_network.jl
`btime` was reporting a small allocation in the ODE rhs function, even for a simple two-variable system. This seems to get rid of it (at least for small systems, on the larger BCR network I'm still seeing allocations).
> return nothing in ODE/SDE functions

- src/reaction_network.jl
I was wondering whether it should be an argument to enable/disable it, but since we are generating the function to match the reaction size, it's fine that it would segfault when used improperly?
> Add `@inbounds` to generated functions

- src/maketype.jl
- src/reaction_network.jl
This should (ultimately)
1. Fix the "+0" terms appearing in ODEs and other generated expressions.
2. Fix the "-1*" terms appearing in ODEs and other generated expressions. Here I just use the `clean_subtractions` function @korsbo wrote in Latexify which he said we should feel free to copy over.
3. Add `@inbounds` for the jump expressions it was still missing on.
@ChrisRackauckas or @TorkelE, would one of you mind taking a look that this seems reasonable? I tested on a few ODE and jump examples and didn't see issues with the generated expressions or solutions, but it would be good to have someone more comfortable working with expressions double check what I've done. If what I'm doing looks ok I'll update the Jacobian and noise generation functions too before merging.
> fix +0s and -1* and add inbounds for jumps

- src/DiffEqBiological.jl
- src/maketype.jl
- src/reaction_network.jl
Added `const ExprValues = Union{Expr,Symbol,Number}` and replaced it in all appropriate places. Should not be any `Any` left now.
> - Replace several instances of "Any" with "ExprValues".

- .travis.yml
- src/DiffEqBiological.jl
- src/network_properties.jl
- test/networkquery_test.jl
- test/runtests.jl
This adds more exported accessors for querying network properties, along with several functions to calculate dependency graphs. 
As we fill this in users should be able to rely less on directly accessing the reaction_network fields, which will be helpful if and when we convert the backend to using ModelingToolkit. (We can just update these functions as appropriate.)
This won't pass tests till a new DiffEqJump release incorporating [67](https://github.com/JuliaDiffEq/DiffEqJump.jl/pull/67). In either case I'll leave it open for a day in case anyone wants to comment on the accessor names.
> Query interface updates

- src/DiffEqBiological.jl
- src/massaction_jump_utils.jl
- src/network_properties.jl
This should finish off a pretty much complete set of functions for querying network properties.
Going forward, I'll update the docs to use these functions instead of `reaction_network` fields. Hopefully this allows us to transition to a different backend like ModelingToolkit down the line without any breaking changes.
> Further network query functions

- src/DiffEqBiological.jl
- src/maketype.jl
- src/network_properties.jl
- src/reaction_network.jl
- test/addreactions_test.jl
- test/runtests.jl
This adds a set of functions for extending a `min_reaction_network` with more species/parameters/reactions, or creating an empty reaction network and then extending it. New functions:
* `@empty_reaction_network`
* `addspecies!`
* `addparam!`
* `addreaction!`
* `add_scale_noise_param!`
I think `addreaction!` could be made more efficient -- right now the user passes an `ExprValues` for the parameter and an `Expr` for the reaction. Basically the two components of one line of the normal macro. So the following two networks should have all of the `min_reaction_network` defined fields equal
```julia
minrn = @min_reaction_network begin
(k*X*(X-1)*(X-2),Y * X), X + 2X ⟺ Y+ X
end k
```
and
```julia
emptyrn = @empty_reaction_network
addspecies!(emptyrn, :X)
addspecies!(emptyrn, "Y") …
```
> Incremental model construction

- src/maketype.jl
- src/reaction_network.jl
For large systems (i.e. many species, certainly O(1000)), it looks to on average be noticeably faster to use `haskey` with the OrderedDict mapping species syms to ints, rather than use `in` with the unordered sym vector. I'll more quantitatively assess how much this helps on a full network once I update `ReactionNetworkImporters.jl` to use the incremental interface.
I only updated this on the incremental interface as it will be slightly slower on small networks, such as one would commonly specify with `@reaction_network`. The speed difference for something small like the repressilator though should be unnoticeable in general...
> further optimize addreaction! for large systems

- src/DiffEqBiological.jl
- src/maketype.jl
- src/network_properties.jl
1. Adds `==` for testing if two networks are the same. Does not currently account for different reaction definitions. i.e. "X+Y-->W" will be considered different then "Y+X-->W". This could be updated later.
2. `ismassaction` test in `addreactions!` uses `issetequal` now.
3. Updated some API documentation as I realized that several routines were not returning data in exactly the form stated by the comment. 
4. Added `productsymstoich` and `substratesymstoich` to allow direct access to what is stored in the reaction_network (i.e. non-allocating access to stoichiometries).
> Better ismassaction test and == test for networks

- src/reaction_network.jl
- test/make_model_test.jl
- test/runtests.jl
This is a first step towards fixing #129, where symbols that correspond to constants in SymEngine lead to incorrect Jacobian terms. Note, this does not completely close the issue, as the same problem can crop up if parameter symbols correspond to SymEngine constants, and this problem also remains for species or parameter symbols when calculating the parameter Jacobian. This should bring us back to the same level of correctness we had on release 3.7.2.
> replace species names in SymEngine with temp symbols

- src/maketype.jl
- src/reaction_network.jl
- test/make_model_test.jl
Fixes the crash mentioned in [discourse](https://discourse.julialang.org/t/solving-highly-stiff-chemical-kinetics-ivp-using-diffeqbiological/25247/18), which was caused by having a system in which the generated Jacobian had a column of zeros leading to an incorrect size for the generated sparse matrix. Turns out I hadn't explicitly set the size of the generated sparse matrix.
I also removed the `jac_prototype` field from within the reaction network as it was not being used (and was explicitly typed as `Nothing` -- we instead use the field within the generated `ODEFunction`).
> add explicit size for sparse matrices 

- src/DiffEqBiological.jl
- src/equilibrate_utils.jl
- src/plot_recipes.jl
- test/equilibrate_test_4.jl
There were some inconsistency in how these were named before. With different names in doc strings, functions and the actual structures.
Now it is
`bifurcation_grid...` (without a s) for all three.
In addition, I reordered the words from `bifurcation_diagram_grid` to `bifurcation_grid_diagram` (to be more consistent with how the input arguments were ordered, as well as how the structure itself is built up).
Just using the same `bifurcations` function for everything, with dispatch depending in what type of argument, might still be the best alternative though. Either way this should be an improvement from what we currently have.
> Make bifurcation diagram variants names more consistent.

- src/maketype.jl
Should fix the error mesh that is cropping up in tutorial II.
> fix empty jump expr Tuple giving error

- src/equilibrate_utils.jl
Previous the stability function simply checked the value of the highest eigenvalue of the Jacobian. For system with n constraints there will however be n eigenvalues equal to zero. Now these are properly ignored by the stability function. This should fix #154. 
(Thanks to Daniel Chen for spotting the issue and helping with the analysis of it)
> Fixing stability calculations for systems with constraints

- src/equilibrate_utils.jl
- test/equilibrate_test_4.jl
While preparing a short tutorial for making bifurcation diagrams I actually discovered an error where some paths were not displayed correctly. It was basically due to be mixing up some parameters in the heuristics. Should be sorted now.
> Fix dp errors

- src/latexify_recipes.jl
The latexify recipe system did not deal properly with chemical arrow notation. This is now fixed.
> Fix broken latexify chemical arrow notation.

- Project.toml
Apparently, the compat range 
```
[compat]
Latexify = "0.11, 1"
```
is not actually a range and does not include `0.12`, etc. This _union_ would have worked if Latexify was not at `0.x.y` but the current compat requirement is prohibiting updates for Latexify.
> Fix broken Latexify compat constraint.

- src/latexify_recipes.jl
I noticed that subscripts, e.g. `x_10`, weren't handled right and this was the answer.
> Fix latexification of derivatives.

- src/DiffEqBiological.jl
- src/networkapi.jl
- src/reaction_network.jl
- test/model_modification.jl
- test/runtests.jl
This builds on https://github.com/SciML/DiffEqBiological.jl/pull/199 by allowing you to reach some of the functionality using the macro. Now:
```julia
rn = @reaction_network
```
creates an empty reaction network.
```julia
rn = @reaction_network p1 p2 p3
```
creates an empty reaction network, and loads it with the parameters `p1`, `p2`, and `p3`.
Also, the macro `@add_reactions` is added, where
```julia
(k1,k2), X ↔ Y
end k1 k2
@add_reactions rn begin
(p,d), X ↔ ∅
end p d
```
is equivalent to
```julia
(k1,k2), X ↔ Y
(p,d), X ↔ ∅
end k1 k2 p d
```
parameters can be declared repeatedly without worry, however, whenever reactions are added, all parameters used have to be marked. E.g. this
```julia
(k1,k2), X …
```
> Enable network expansion macros

- Project.toml
- src/DiffEqBiological.jl
- src/reaction_network.jl
- test/make_model.jl
- test/plotting.jl
- test/runtests.jl
@TorkelE we had discussed adding back in `I`, but I noticed it was not allowed still. Is this there any reason to not allow it? 
I've also removed a large number of package imports that are no longer needed, or only needed in tests. We should let tests finish to confirm I didn't miss anything.
> Allow I as a variable and remove unneeded imports

- README.md
Gotten comments before from non-Github users and non-Julia folk that they couldn't find the docs because they didn't know to look for the blue badges, so it's always good to put these few lines.
> Add documentation mentions to the README

- Project.toml
- src/Catalyst.jl
- src/graphs.jl
Some caveats:
1. Adds Catlab dependency since `GraphViz.jl` is no longer maintained. This means users must separately install the `GraphViz` command line tools.
2. Of the Lightgraph plotting tools very few seem to be actively maintained. Maybe we could use `GraphPlot.jl` instead.
3. Like all the graph libraries it does not generate graph windows with figures from the REPL, only saveable text. Figures can be saved, or generated within Jupyter.
Ex:
```julia
using Catalyst, Catlab.Graphics.Graphviz
α, S + I --> 2I
β, I --> R
end α β
Graph(rn)
```
in Jupyter gives:
Here orange nodes denote reactions and the labels on edges give the stoichiometry. Connections coming through the `rate` won't appear (i.e. Hill functions or such). We should think about how to …
> Generation of graphviz graphs

- src/graphs.jl
```julia
hillr(P₃,α,K,n), ∅ --> m₁
hillr(P₁,α,K,n), ∅ --> m₂
hillr(P₂,α,K,n), ∅ --> m₃
(δ,γ), m₁ ↔ ∅
(δ,γ), m₂ ↔ ∅
(δ,γ), m₃ ↔ ∅
β, m₁ --> m₁ + P₁
β, m₂ --> m₂ + P₂
β, m₃ --> m₃ + P₃
μ, P₁ --> ∅
μ, P₂ --> ∅
μ, P₃ --> ∅
end α K n δ γ β μ;
savegraph(Graph(rn),fname,"png")
```
gives
with red dashed arrows for species that appear within the rate, but do not technically have stoichiometric coefficients.
> Add edges for rate deps

- test/solve_SDEs.jl
At the risk of overdoing the tests...
This basically tests the noise scaling functionality recently added in MTK, but "in action". That is, it simulates a network with different levels of noise scaling and tests that the variation of the distributions scales properly.
> Add noise scaling tests.

- src/reaction_network.jl
This is how I write it on the paper. Maybe even `:⥋` and `:⥊` can be useful.
The idea comes from https://github.com/zdroid/ChemEquations.jl, as some people suggested me to try integrate it with reaction networks from this repository.
> Add :⇌, :⇋ to double_arrows

- test/api.jl
A coverage increase which comes at no additional costs.
> Use numspecies and numparams in API tests

- test/solve_ODEs.jl
- test/solve_SDEs.jl
- test/solve_jumps.jl
- test/steady_state_problems.jl
Adds a simple test each for ODE, SDE, Jump, and SteadyState Problems, testing that they work fro systems without parameters.
> Add no parameter tests

- src/Catalyst.jl
- src/graphs.jl
- src/latexify_recipes.jl
When the Graphviz jll works more widely (it apparently doesn't currently work for many formats on Macs), we can switch to using it directly.
> Switch Catlab to imports

- test/runtests.jl
Let's turn these off temporarily until we can figure out how to make them more robust to differences that arise between OSes...
> don't run Latexify tests

- Project.toml
- docs/src/tutorials/generated_systems.md
- src/Catalyst.jl
- src/networkapi.jl
- test/latexify.jl
- test/make_model.jl
- test/solve_SDEs.jl
needs https://github.com/SciML/ModelingToolkit.jl/pull/720 and the latest release of SymbolicUtils.jl
> Updates for upstream breaking changes

- docs/make.jl
Modified the `docs/make.jl` file
```
makedocs(
sitename = "Catalyst.jl",
authors = "Samuel Isaacson",
format = Documenter.HTML(mathengine=Documenter.Writers.HTMLWriter.MathJax(), prettyurls = (get(ENV, "CI", nothing) == "true")),
modules = [Catalyst,ModelingToolkit],
doctest = false,
clean = true,
pages = Any[
"Home" => "index.md",
"Tutorials" => Any[
"tutorials/using_catalyst.md",
"tutorials/basics.md",
"tutorials/models.md",
"tutorials/basic_examples.md",
"tutorials/advanced.md",
"tutorials/generated_systems.md",
"tutorials/advanced_examples.md",
"tutorials/bifurcation_diagram.md"
],
"API" => Any[
"api/catalyst_api.md"
]
]
)
```
> add bifurcation docs link

- src/reaction_network.jl
Currently when using `@reaction_network` with no reactions and one of the parameters is reserved Julia throws an error before the desired error message is printed out. This is due to the code trying to access a nonexistent variable which has been removed in this version.
> Fixed error message for @reaction_network with no reactions

- Project.toml
- docs/src/api/catalyst_api.md
- docs/src/tutorials/generated_systems.md
- src/networkapi.jl
- src/reaction_network.jl
- test/make_model.jl
Closes https://github.com/SciML/Catalyst.jl/issues/317
Seems to work for non-empty networks. Empty networks would require a breaking change to drop allowing an empty network that has parameters defined (which seems reasonable to me since parameters can be subsequently added if needed). @TorkelE do you remember why we allowed `@reaction_network k1 k2 k3` to work and make an empty system with parameters `k1`, `k2`, `k3`?
> Allow sys names and other API fixes

- src/graphs.jl
- test/graphs.jl
@giordano does this look right to you in the case that the Graphviz jll is installed? This is following up on the discussion in
https://github.com/JuliaPackaging/Yggdrasil/issues/1428
Thanks!
> use correct syntax for graphviz jll

- .gitignore
- Project.toml
- src/Catalyst.jl
- src/networkapi.jl
- test/conslaws.jl
- test/runtests.jl
Following onwards from [here](https://github.com/SciML/ModelingToolkit.jl/issues/965) I've added some code taken from [here](https://github.com/kaandocal/FiniteStateProjection.jl/) to detect conservation laws for a reaction system together with a rudimentary unit test for Catalyst. 
- There are multiple equivalent matrices of conservation laws for most systems, afaik there's no way to guarantee which one you're going to get
- It introduces a dependency on AbstractAlgebra.jl
- This will not be very efficient for large (>100 species) systems
Going forward it would be great if we could add functionality to simplify a system based on a conservation law. Basically I was thinking of something like a function `structsimplify(rn, species, cons)` that takes a reaction network and a list of species …
> Adding support for conservation law

- test/api.jl
ModelingToolkit now requires explicit time dependence for variables in time-dependent systems. See https://github.com/SciML/ModelingToolkit.jl/pull/1064
> Use explicit time dependence

- src/networkapi.jl
- src/reaction_network.jl
used with https://github.com/SciML/ModelingToolkit.jl/pull/1129 
should fix the downstream test issues there. 
not sure how to make CI use PRs instead of main though, so this will fail
> update ReactionSystem constructors for defaults

- src/registered_functions.jl
With this pr these are possible:
`mm`, `Mm`, `MM`
`mmR`, `MmR`, `MMR`, `mmr`, `Mmr`, `MMr`
`hill`, `Hill`
`hillR`, `HillR`, `hillr`, `Hillr`
`hillC`, `hillAR`, `HillC`, `HillAR`, `hillc`, `hillar`, `Hillc`, `Hillar`
This is way more than what's actually needed, which is only really useful to cater to people with obscure preferences. If anyone has any opinions we could remove a couple.
> Fix function names that are enabled

- src/reactionsystem.jl
This will be necessary (in order to take advantage of unit validation) when [ModelingToolkit.jl#1156](https://github.com/SciML/ModelingToolkit.jl/pull/1156#) lands.
> ModelingToolkit unit validation logic

- Project.toml
- src/Catalyst.jl
- src/networkapi.jl
- src/reactionsystem.jl
- test/runtests.jl
- test/units.jl
I also added a `show` definition for `Reaction`s that prints out stuff like
```
Reaction{Any, Int64}: γ, A + B --> 2B
```
so a user could easily round-trip to/from the DSL. (I kept the summary with type info, but could drop that from `show` if anyone thinks that makes sense.)
> Unit validation and tests 

- Project.toml
- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/networkapi.jl
- test/api.jl
from https://github.com/SciML/Catalyst.jl/issues/386#issuecomment-904876595
example. We use a second  function argument of type `Bool` to switch `sparsity` on or off. Default is dense representation as earlier, i.e.`sparsity=false`
```julia
k₁, 2A --> B
k₂, A --> C
k₃, C --> D
k₄, B + D --> E
end k₁ k₂ k₃ k₄
julia> substoichmat(rn)   # usual function or substoichmat(rn,false)
4×5 Matrix{Int64}:
2  0  0  0  0
1  0  0  0  0
0  0  1  0  0
0  1  0  1  0
julia> substoichmat(rn,true)     # sparse representation
4×5 SparseMatrixCSC{Int64, Int64} with 5 stored entries:
2  ⋅  ⋅  ⋅  ⋅
1  ⋅  ⋅  ⋅  ⋅
⋅  ⋅  1  ⋅  ⋅
⋅  1  ⋅  1  ⋅
```
> Sparse representation of `stoichiometric matrices` functions and matrices in complex-based functions

- src/networkapi.jl
- src/reactionsystem.jl
- test/reactionsystem_components.jl
I'm not sure what happened in that last PR as this was the same branch and all committed; I must have forgotten to push them to the PR...
This should fix the previous PR to (hopefully) correctly namespace `species`, `reactionparams` and `reactions` when there are nested subsystems.
> attempt 2 at naming for compositional systems

- docs/src/index.md
The doc had a reaction network importer link. Previously it was to https://github.com/isaacsas/ReactionNetworkImporters.jl but I presume the target should be https://github.com/isaacsas/ReactionNetworkImporters.jl ?
> Change ReactionNetworkImportes link

- HISTORY.md
- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/networkapi.jl
- src/reactionsystem.jl
- test/api.jl
1. Adds `hash` on reactions so they work properly in dictionaries and sets, fixing `issetequal` for collections of them.
2. Uses `convert_system` for upconverting non-ReactionSystem subsystems when possible, throwing an error when an appropriate `convert_system` does not exist.
3. Added back exports of depreciated functions (we can keep them exported with warnings for one major release cycle).
> Fix reaction equality in sets and add upconversion to ODESystems in convert

- HISTORY.md
- src/reactionsystem.jl
- test/reactionsystem.jl
Closes https://github.com/SciML/Catalyst.jl/issues/425.
CC @anandijain
> Simplified ReactionSystem constructor

- HISTORY.md
- docs/src/api/catalyst_api.md
- docs/src/tutorials/generated_systems.md
- docs/src/tutorials/models.md
- src/Catalyst.jl
- src/graphs.jl
- src/latexify_recipes.jl
- src/networkapi.jl
- src/reaction_network.jl
- src/reactionsystem.jl
- test/dsl.jl
- test/latexify.jl
- test/reactionsystem_components.jl
- test/runtests.jl
Enables `extend`ing `ReactionSystem`s with algebraic and ODE constraints. While we currently can have sub-systems of algebraic (or even ODE) constraints, this is annoying for specifying algebraic equations to couple systems (since everything needs to get parent scoped). i.e. imagine wanting to hook three systems representing genes together, conceptually this is not necessarily a hierarchical system, but more a collection of parallel systems with coupling equations one level up. (This wouldn't necessarily be an issue if we could make the top-level system a `NonlinearSystem`, but currently MT requires sub-systems to have the same type, so top-level systems must be `ReactionSystem`s.)
This PR allows attaching to a `ReactionSystem` an internal constraint system, which is considered at the …
> Constraints, flattening, and extending for ReactionSystems

- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/reaction_network.jl
- src/registered_functions.jl
- test/dsl.jl
Currently
```julia
rn = @reaction_network
k*B, A --> B
end k
```
will error that `B` is unknown. This causes problems in using the DSL in component-based systems, where there may be variables that one wants to use that correspond to species in other components. 
While this PR is breaking, our next release will need to be breaking anyways due to other recent changes. The PR changes the DSL so that anything not declared a parameter is now treated as a chemical species. This isn't a particularly disruptive change since previously this would have errored anyways.
@TorkelE could you double check the macro usage here? I wasn't sure the best way to determine if a Symbol is a valid variable name in general, so just tested against the `forbidden_symbols` and the current list of parameters.
> Make undefined variables in DSL become species

- HISTORY.md
- src/networkapi.jl
- src/reactionsystem.jl
- test/reactionsystem.jl
Handles https://github.com/SciML/ModelingToolkit.jl/issues/1335 for ReactionSystems and adds `var_to_name` to enable `sys.observable_name` and `@unpack observable_name = sys`. I also made the unit checking slightly more efficient in the case of no units.
> Add var_to_name field

- HISTORY.md
Now the history file starts like this:
- **BREAKING:** The order of the parameters in the `ReactionSystem`'s `.ps` field has been changed (only when created through the `@reaction_network` macro). Previously they were ordered acording to the order with which they appeared in the macro. Now they are ordered acoridng the to order with which the appeard after the `end` part. E.g. in
```julia
(p,d), 0 <--> X
end d p
```
previousl the order was `[p,d]`, which now it is `[d, p]`.
- Added support for `@unpack observable_variable = rn` and
`rn.observable_variable`. This requires a new inner constructor definition for
`ReactionSystem`s, but is not considered breaking as the inner constructor is
considered private.
- Support added for ModelingToolkit 7 and Symbolics 4.
> Add history entry for paraemter order change.

- src/networkapi.jl
- test/model_modification.jl
Variables added with addparam! or addspecies! can now be accessed
using Base.getproperty.
The addparams! and addspecies! methods now use
ModelingToolkit.process_variables! to update the var_to_name
dictionary when variables are added.
> Fix access to variables added with addparam! or addspecies!

- src/reaction_network.jl
- src/reactionsystem.jl
- test/dsl.jl
...into `Expr` in `make_reaction_system` to ensure that it is properly qualified when `make_reaction_system` is used
from other modules.
This makes
```julia
julia> ex = quote
(Ka, Depot --> Central)
(CL / Vc, Central --> 0)
end;
julia> Base.remove_linenums!(ex);
julia> eval(Catalyst.make_reaction_system(ex, (:CL, :Vc, :Ka)))
Model ##ReactionSystem#274 with 2 equations
States (2):
Depot(t)
Central(t)
Parameters (3):
CL
Vc
Ka
```
work.
(I've also removed some white space while here, so please click the first commit when reviewing the diff).
> Interpolate make_ReactionSystem_internal

- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/networkapi.jl
- src/reactionsystem.jl
- test/api.jl
- test/dsl.jl
Closes https://github.com/SciML/Catalyst.jl/issues/464.
When using the DSL, not having variables and parameters defined in the current context makes it annoying to construct parameter / initial condition mappings. This PR adds helpers to make this easier. 
```julia
α, S + I --> 2I
β, I --> R
end α β
defs = [:S => 999.0, :I => 1.0, :R => 0.0, :α => 1e-4, :β => .01]
setdefaults!(rn, defs)
op = ODEProblem(rn, [], tspan, [])
sol = solve(op, Tsit5())
```
The docs make clear that `setdefaults!` only acts on states and parameters at the level of a given system, so needs to be manually called on sub-systems in hierarchical models, or used after flattening.
Also added the ability to unpack all variables and parameters into the current context, e.g.
```julia
rn = …
```
> fix DSL annoyances

- HISTORY.md
- src/Catalyst.jl
- src/reaction_network.jl
- test/dsl.jl
Allows
```julia
rx = @reaction k*v, A + B --> C + D
```
where `k` and `v` will be parameters and `A`, `B`, `C` and `D` will be variables.
Interpolation of existing parameters/variables also works
```julia
@parameters k b
@variables t A(t)
ex = k*A^2 + t
rx = @reaction b*$ex*$A, B --> C
```
Any symbols arising in the rate expression that aren't interpolated are treated as parameters, while any in the reaction part (`A + B --> C + D`) are treated as species. 
We could potentially make a (future) breaking release that tries to detect if a symbol is defined in the calling module, and if so uses it. If not defined, it defines it per the convention above (avoiding the need to use `$A` like above). I think it makes sense to add that for both this macro and the `@reaction_network` macro at the …
> @reaction macro

- src/reaction_network.jl
- src/reactionsystem.jl
- test/dsl.jl
- test/reactionsystem.jl
- test/solve_ODEs.jl
There is a decision to be made on the default conventions. 
Prior to this PR we always scaled ODE and jump rates by a combinatorial factor, treating the rate constants as microscopic rate constants. In this way our ODE models are the mean-field of our jump models.
However, such a scaling doesn't seem to me to make sense when having non-integer stoichiometry coefficients (unless we want to restrict non-integer stoichiometry to products and not allow for reactants, or scale by a gamma function which seems weird). 
In this PR I set the conventions as:
1. All the reactant and product stoichiometry of a given reaction are promoted to the same type.
2. If this type is an integer we rescale by default as we currently do.
3. If this type is not integer we error if the user does not explicitly …
> Allow float stoichiometry

- src/reaction_network.jl
Since at some point we switched compatibility to 1.6 on up the check is no longer needed.
> remove new 1.6 arrow checks

- HISTORY.md
- Project.toml
- docs/src/api/catalyst_api.md
- docs/src/tutorials/symbolic_stoich.md
- src/Catalyst.jl
- src/networkapi.jl
- src/reaction_network.jl
- src/reactionsystem.jl
- src/registered_functions.jl
- test/api.jl
- test/conslaws.jl
- test/model_modification.jl
`ReactionSystem`s store a new (internal) field, `networkproperties`, that caches all the needed info for the various `convert` methods to eliminate out conservation laws (along with also being used to cache various network properties in the API). I left it this way as it didn't really seem to make sense to try to eliminate species at the `ReactionSystem` level (i.e. reactions would then contain algebraic expressions for the eliminated species as their substrates). Happy to consider alternative designs if there are better / more standard approaches.
TODO:
```julia
k, A + B --> C
k2, C --> A + B
end k k2
conservationlaws(rn)
get_networkproperties(rn)
```
giving
```
Conserved Equations: 
B(t) ~ A(t) + _ConLaw[1]
C(t) ~ _ConLaw[2] - A(t)
Net stoichiometry matrix: …
```
> Elimination of conservation laws

- src/reactionsystem.jl
- test/reactionsystem.jl
- test/symbolic_stoich.jl
Should close https://github.com/SciML/Catalyst.jl/issues/528.
This can definitely be better optimized, and `ModelingToolkit.JumpSystem` should get updated to be able to take dependency graphs as an optional input (since we are already calculating them here). I'll plan to circle back and better optimize down the line.
> use dependency graph to classify VariableRateJumps

- src/reactionsystem.jl
All reaction complexes have type parameter `<: Integer`
> Remove unnecessary type parameter

- .github/workflows/CompatHelper.yml
Why is this compat helper script much more complicated than e.g [LinearSolve.jl](https://github.com/SciML/LinearSolve.jl/blob/main/.github/workflows/CompatHelper.yml )?
Would any of the other SciML packages benefit from the extra complexity here?
> [skip ci] doc compats

- docs/src/faqs.md
- docs/src/tutorials/advanced.md
- src/reaction_network.jl
- test/make_model.jl
Since these can be written on a normal keyboard, `=>` and `<=` are now enabled when ignoring the law of mass action and only using the rate. I've added tests and updated the docs, should all should be ready.
I would have added `<=>` as well, but unfortunately `X <=> X` is not a valid Julai expression. If we are really keen on this we could try to moot for this (like `<-->` and `<--`, although these were way more important additions).
> Enable `=>` and `<=` to ignore law of mass action in DSL

- docs/Project.toml
- docs/make.jl
- docs/src/api/catalyst_api.md
- docs/src/catalyst_functionality/dsl_description.md
- src/latexify_recipes.jl
- test/latexify.jl
Closes https://github.com/SciML/Catalyst.jl/issues/595
This drops the mhchem package specialized reaction commands, switching to extensible arrows. It now outputs displayable reactions across Documenter, Jupyter browser notebooks, VSCode Jupyter notebooks, and Pluto. 
Unfortunately, Pluto and Documenter with Mathjax don't seem to render "\xrightleftharpoons" with a reversible arrow that stretches. However, I could switch Documenter back to Katex since we dropped mhchem and then the command stretches properly. 
There isn't much we can do unless we want to switch away from harpoon arrows to something like "\xleftrightarrow" (but this loses the arrow directionality so seems like the worse choice of current options).
> Drop mhchem

- src/networkapi.jl
- src/reactionsystem.jl
- test/reactionsystem.jl
Closes https://github.com/SciML/Catalyst.jl/issues/547
Closes https://github.com/SciML/Catalyst.jl/issues/516
> Disallow repeated reactants and making hashing order independent 

- docs/src/catalyst_functionality/dsl_description.md
- test/reactionsystem_structure/reactionsystem.jl
It is possible for an initial condition to be a parameter:
```julia
using Catlyst
@species X(t)=1.0
@parameters p=1.0 d=0.1
p, 0 --> X
d, X --> ∅
end
using DifferentialEquations, Plots
u0 = []
tspan = (0.0, 10.0)
p = []
oprob = ODEProblem(rn, u0, tspan, p)
sol = solve(oprob)
plot(sol)
```
which is actually quite neat. We don't document (or test) this feature though, so I have added both.
> Documentation of initial conditions that depend on a parameter

- test/dsl/dsl_basics.jl
- test/miscellaneous_tests/symbolic_stoichiometry.jl
- test/model_simulation/simulate_ODEs.jl
- test/model_simulation/simulate_PDEs.jl
- test/model_simulation/simulate_jumps.jl
- test/reactionsystem_structure/higher_order_reactions.jl
- test/reactionsystem_structure/reactionsystem.jl
I went through the tests, trying to see if there is anything that can be cut. Most of it is complication time, however, I found some Jump simulations across two files where I could remove some probably superfluous repeats of the simulations. It only removed like 1 minute in the end, had hoped to gain more.
While I went through stuff I removed some unnecessary statements, and only added a few missing StableRNG uses (where `rand` was called without StableRNG input).
> Test cleanup

- docs/Project.toml
- docs/src/catalyst_applications/advanced_simulations.md
- docs/src/catalyst_applications/bifurcation_diagrams.md
- docs/src/catalyst_applications/homotopy_continuation.md
- docs/src/example_networks/smoluchowski_coagulation_equation.md
- docs/src/introduction_to_catalyst/catalyst_for_new_julia_users.md
- docs/src/introduction_to_catalyst/introduction_to_catalyst.md
Preparing for the PEtab doc update.
- Update the version of packages used for building docs.
- Updates the Bifurcation tutorial for v 0.3.
- Adds references at the bottom of certain doc pages (e.g. book on bifurcations at the bottom of the bifurcation tutorial).
- - Makes the coagulation tutorial use the same reference style (for stuff at the bottom) as other doc pages.
> General doc update

- test/miscellaneous_tests/nonlinear_solve.jl
- test/runtests.jl
Currently, we do not really test the conversions to `NonlinearSystem`s and `NonlinearProblem`s and their solutions. We do some tests on `SteadyStateProblem`s, but these are kind of deprecated anyway.
This PR adds some tests to this. The tests should be good, but need to check whether the tolerances are not good enough that the outputs are close enough to 0. If not, I will have to make stuff more lenient.
> Add tests for NonlinearSolve and NonlinearProblem

- HISTORY.md
- docs/src/catalyst_functionality/dsl_description.md
- docs/unpublished/pdes.md
- ext/CatalystBifurcationKitExtension/bifurcation_kit_extension.jl
- src/graphs.jl
- src/latexify_recipes.jl
- src/networkapi.jl
- src/reactionsystem.jl
- src/registered_functions.jl
- test/dsl/dsl_basics.jl
- test/dsl/dsl_model_construction.jl
- test/dsl/dsl_options.jl
- test/network_analysis/conservation_laws.jl
- test/programmatic_model_creation/component_based_model_creation.jl
- test/programmatic_model_creation/programmatic_model_expansion.jl
Fixes some incorrect usage of fields in MTK systems instead of getters.
> warning fixes

- docs/src/inverse_problems/petab_ode_param_fitting.md
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.
> Remove minus sign in ub=1e-2 and unneeded 'as'

- src/reactionsystem.jl
- test/reactionsystem_structure/reactionsystem.jl
Adds a `metadata::Any` field to `ReactionSystem`s. Currently have no direct use. However, it can be used by downstream packages. Also, it makes `ReactionSystem` conform to the standard of various MTK System types which have this field.
> Add reaction system metadata

- HISTORY.md
- docs/src/api/catalyst_api.md
- src/Catalyst.jl
- src/expression_utils.jl
- src/reaction_network.jl
- src/reactionsystem.jl
- src/registered_functions.jl
- test/dsl/dsl_basics.jl
- test/reactionsystem_structure/reactions.jl
- test/runtests.jl
The `Reaction` type now have a `.metadata` field:
```julia
"""
Contain additional data, such whenever the reaction have a specific noise-scaling expression for
the chemical Langevin equation.
"""
metadata::Dict{Symbol, R}
```
I would have used `Base.ImmutableDict`s, but there are problems with regards to these: https://discourse.julialang.org/t/create-immutabledict-with-values-of-differenrt-types/107831
The metadata can be accessed via the following functions:
```
get_metadata_dict
has_metadata
get_metadata
```
Metadata can either be added as an optional argument when creating `Reactions`s programmatically:
```julia
using Catalyst
@variables t
@parameters k
@species X(t) X2(t)
metadata = Dict(:noise_scaling => 0.0)
r = Reaction(k, [X], [X2], [2], [1]; metadata=metadata)
```
Here, the …
> [v14 ready] Implement metadata for `Reactions`s

- docs/src/api.md
- src/Catalyst.jl
- src/reactionsystem.jl
- test/reactionsystem_core/coupled_equation_crn_systems.jl
Returns all `Equation`s in a reaction system (like `nonspecies` returns variables). Also adds some additional tests for this kind of accessor functions on couple CRN/equation models.
> Add `nonreaction` function

- src/network_analysis.jl
- test/network_analysis/conservation_laws.jl
Add a `conservedquantity = true` metadata to all conserved quantity parameters. These permits e.g. detecting these in e.g. StrucuralIdentifiability outputs, and eliminating them from here.
> Add `conservedquantity` metadata

- docs/src/model_creation/chemistry_related_functionality.md
- src/Catalyst.jl
- src/chemistry_functionality.jl
- test/miscellaneous_tests/reaction_balancing.jl
Creates a function `balance_system`, which takes a `ReactionSystem` and returns a version with all its reactions balanced.
```julia
rs = @reaction_network begin
@species C(t) O(t) H(t)
@compounds begin
H2(t) = 2H
CH4(t) = C + 4H
O2(t) = 2O
CO2(t) = C + 2O
H2O(t) = 2H + O
end
1.0, C + H2 --> CH4
2.0, CH4 + O2 --> CO2 + H2O
end
rs_balanced = balance_system(rs)
```
> Full system balancing

- src/reaction.jl
- test/reactionsystem_core/reaction.jl
I have added two more `Reaction` metadata that we support with getters:
- `description`
- `misc`
There are two main uses of this PR:
- These two metadata should be usable by the user to support any metadata they would like to use, without us having to support the addition of user-designated metadata.
- They are good metadata to introduce the concept of reaction metadata in the docs (rather than noise scaling, which is non-obvious what it is). This way I do not have to introduce `Reaction` metadata in the SDE tutorials.
> Add two new reaction metadata

- src/reaction.jl
- test/reactionsystem_core/reaction.jl
The `get_variables` function is currently defined for `Equation`s but not `Reaction`s. I've added it. It goes through all fields, checking and adds all symbolic variables to an output vector.
> Add `get_variables` dispatch for `Reaction`

- src/reactionsystem.jl
- test/simulation_and_solving/simulate_SDEs.jl
Updates the noise scaling feature with:
- Ensures that species/variables/parameters introduced by the noise scaling metadata is always properly added to the new system.
- Add additional tests.
> Noise scaling update

- HISTORY.md
- docs/src/api.md
- src/Catalyst.jl
- src/reactionsystem.jl
- test/compositional_modelling/component_based_model_creation.jl
- test/dsl/dsl_advanced_model_construction.jl
- test/miscellaneous_tests/api.jl
- test/reactionsystem_core/coupled_equation_crn_systems.jl
Rename `reactionparams`, `numreactionparams`, and `reactionparamsmap` to `reactionsystemparams`, `numreactionsystemparams`, and `reactionsystemparamsmap`, respectively.
> Rename `reactionparams` and similar functions

- docs/src/inverse_problems/optimization_ode_param_fitting.md
- test/reactionsystem_core/events.jl
- test/reactionsystem_core/higher_order_reactions.jl
- test/reactionsystem_core/symbolic_stoichiometry.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/simulation_and_solving/simulate_jumps.jl
Updates tutorial on parameter fitting using optimization
> Optim param fitting doc

- docs/pages.jl
- src/Catalyst.jl
- src/spatial_reaction_systems/lattice_jump_systems.jl
- src/spatial_reaction_systems/utility.jl
- test/runtests.jl
- test/spatial_reaction_systems/lattice_reaction_systems_jumps.jl
To avoid rebasing hell this is simply a new version of https://github.com/SciML/Catalyst.jl/pull/663. You might have some input on simpler ways to compute the (non-spatial) mass action Jumps @isaacsas, but otherwise, this is good to go. Currently vertex parameters must be uniform across the grid (and this is enforced). Once @Vilin97 have his PRs merged over at JumpProcesses, this requirement can be lightened. 
I have added support for spatial jumps. Creating and solving a problem is relatively easy:
```julia
using Catalyst, Graphs, JumpProcesses
SIR_system = @reaction_network begin
α, S + I --> 2I
β, I --> R
end
trS = @transport_reaction dS S
trI = @transport_reaction dI I
lattice = Graphs.grid([2, 2])
lrs = LatticeReactionSystem(SIR_system, [trS, trI], lattice)
u0 = [:S => [999, 1000, …
```
> [v14 ready] RDME and graph SSAs

- docs/Project.toml
- docs/src/steady_state_functionality/bifurcation_diagrams.md
Now we can (supposedly) use `opts_br` instead of `(args...) -> opts_br` as input, so modify the doc accordingly
> Update bifurcationkit doc page

- src/reactionsystem_conversions.jl
- test/dsl/dsl_basic_model_construction.jl
- test/network_analysis/conservation_laws.jl
- test/simulation_and_solving/simulate_ODEs.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/simulation_and_solving/simulate_jumps.jl
- test/test_networks.jl
Adds additional tests of conservation laws, especially relating to when attempting to simulate them. 
Only non-test change is that 
```julia
convert(JumpSystem, rs; remove_conserved = true)
```
now throws an `ArgumentError` (as opposed to a generic error). The reason was that this was I could write a test to check that it does throw a specific error (and not just one from wrong input).
> Expand conservation law tests

- docs/pages.jl
- docs/src/model_creation/examples/hodgkin_huxley_equation.md
minimum changes for docs to pass
> Proposed hh model example changes

- src/reaction.jl
- test/reactionsystem_core/reaction.jl
- test/reactionsystem_core/reactionsystem.jl
- Permits `[]` and `nothing` to be used interchangeably (previously there were some cases which unintentionally would not work).
- Ensures that the `Reaction` structure is concretely typed.
> Update `Reaction` constructor

- docs/pages.jl
- docs/src/faqs.md
reuploaded due to a rebase issue
> Proposed FAq doc updates

- test/visualisation/latexify.jl
Fixes the latexify tests. Mostly the errors were due to tabs.
There are a couple that we technically can generate passing tests for, however, the display is non-desired (for various reasons). For these I have just created a `test_broken` and linked the relevant issue.
The display of the tests that are marked as passing looks fine:
> [v14 - Ready] Fixes latexify tests

- src/spatial_reaction_systems/lattice_jump_systems.jl
- test/runtests.jl
Hopefully fixes the warning when calling `using Catalyst`.
> fix Catalyst using warning

- docs/src/model_creation/model_file_loading_and_export.md
- ext/CatalystStructuralIdentifiabilityExtension/structural_identifiability_extension.jl
- src/dsl.jl
- src/reactionsystem_serialisation/serialise_fields.jl
- src/spatial_reaction_systems/spatial_reactions.jl
- test/dsl/dsl_advanced_model_construction.jl
- test/miscellaneous_tests/reactionsystem_serialisation.jl
- test/miscellaneous_tests/units.jl
- test/reactionsystem_core/events.jl
- test/reactionsystem_core/reaction.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/spatial_modelling/lattice_reaction_systems.jl
- test/spatial_modelling/spatial_reactions.jl
Some `@variables t` to `t = default_t()` were missed, and the DSL needed updating in places to use `default_t()`.
@TorkelE please review to make sure I haven't screwed up the serialization part in particular.
> make `t` a parameter now

- docs/src/spatial_modelling/lattice_reaction_systems.md
- docs/src/spatial_modelling/lattice_simulation_plotting.md
change path so that they should be displayed on github
> Fix spatial sim aniamtions in doc

- docs/src/model_creation/chemistry_related_functionality.md
- docs/unpublished/pdes.md
- test/dsl/dsl_options.jl
- test/miscellaneous_tests/compound_macro.jl
- test/miscellaneous_tests/reactionsystem_serialisation.jl
- test/reactionsystem_core/coupled_equation_crn_systems.jl
- test/reactionsystem_core/custom_crn_functions.jl
- test/reactionsystem_core/reactionsystem.jl
- test/spatial_modelling/simulate_PDEs.jl
Primarily in the test files. These were the last cases I could find, but there might possibly be more that I missed. Need to read through tomorrow as well to check it looks OK.
> More t is now a parameter test

- docs/src/api.md
- docs/src/faqs.md
- docs/src/model_creation/chemistry_related_functionality.md
- docs/src/model_creation/dsl_advanced.md
- src/spatial_reaction_systems/spatial_reactions.jl
Some updates to the API. Intended to fix https://github.com/SciML/Catalyst.jl/issues/990, but turns out most of those lack docstrings in MTK, which is probably the reason they were left out in the first place, so couldn't actually add those here.
> Api update

- src/reactionsystem_conversions.jl
Currently, MTK requires a matrix to be `Matrix{Num}`, which is not good. However, and update which changes so that `Matrix{Any}` will work again seems like it is out soon. When it is we can merge this and things should be all good again.
> Revert SDE change

- docs/src/api.md
- docs/src/introduction_to_catalyst/introduction_to_catalyst.md
- docs/src/model_creation/examples/basic_CRN_library.md
- docs/src/model_creation/parametric_stoichiometry.md
- src/Catalyst.jl
- src/plotting.jl
I just copied over the minimal set of stuff from DisplayAs that we need so we don't have to rely on it. The code is pretty simple so I think should be fine to keep in Catalyst (and DisplayAs is MIT so compatible).
Note that using PNG's means we don't need all the `plotdensity` stuff any more or to use `saveat`, but we do need to up the default `dpi` as otherwise the plots are a bit blurry when converted.
> Long jump plotting fix

- test/reactionsystem_core/parameter_type_designation.jl
With https://github.com/SciML/ModelingToolkit.jl/pull/2908, tunables are being merged into one `Vector{T}`, where `T` is some floating point number. This is because tunables are intended for optimization and sensitivity analysis, but AD doesn't work for integers. Not splitting into `Tuple{Vector{T1}, Vector{T2}}` also has performance benefits for sensitivity analysis, and helps reduce a significant number of bugs. Array tunables are also concatenated into this vector. Accessing these functions is done through a view to prevent unnecessary performance overhead, even in MTK's generated functions.
To this end, parameters are promoted to a common type. Overly specific type annotations are also in general invalid, since the parameters could also be duals.
This PR is a draft so it can be rerun …
> test: remove unnecessarily specific parameter type annotations

- ext/CatalystHomotopyContinuationExtension/homotopy_continuation_extension.jl
- src/Catalyst.jl
- src/chemistry_functionality.jl
- src/dsl.jl
- src/latexify_recipes.jl
- src/registered_functions.jl
- test/dsl/dsl_options.jl
- test/miscellaneous_tests/compound_macro.jl
fixes some remaining cases where `arguments` should be `sorted_arguments` with the new Symbolics update
> `arguments` -> `sorted_arguments` updates

- src/dsl.jl
- test/dsl/dsl_advanced_model_construction.jl
This introduces a bunch of intermediate variables to store inputs to `make_ReactionSystem_internal`, with the goal of making the generated expression easier to read when debugging. It also makes the creation of `t` the first thing in the generated code, which should be a first step to allowing time-dependent parameters (something MTK is working on better supporting).
> cleanup DSL generated expression for readability

- docs/src/model_creation/dsl_advanced.md
- docs/src/model_creation/examples/programmatic_generative_linear_pathway.md
- docs/src/model_creation/examples/smoluchowski_coagulation_equation.md
- src/dsl.jl
- src/network_analysis.jl
- src/reactionsystem.jl
- test/dsl/dsl_advanced_model_construction.jl
- test/dsl/dsl_options.jl
- test/network_analysis/conservation_laws.jl
- test/reactionsystem_core/reactionsystem.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/test_functions.jl
- test/upstream/mtk_problem_inputs.jl
Closes https://github.com/SciML/Catalyst.jl/issues/1051
Not handled yet
WIth this PR the DSL will still scalarize non-parameters, but I believe this is consistent with MTK now.
> drop scalarizing

- HISTORY.md
- docs/src/inverse_problems/structural_identifiability.md
- test/extensions/bifurcation_kit.jl
- test/extensions/homotopy_continuation.jl
- test/runtests.jl
Fixes the tests that have been broken by recent updates. 
The long running for identifiability analysis has to do with us using array variables for representing unknown quantities, and there seems to be a problem with this (likely related to recent updates). Might be easiest to simple rewrite code to not use that, will have a look.
> Fix broken tests

- src/Catalyst.jl
- src/reaction.jl
- src/reactionsystem.jl
- test/compositional_modelling/component_based_model_creation.jl
Also switches us to using `ModelingToolkit.collect_vars!` for everything but events (where there is no such functionality).
> Add compose dispatch and constent handling of scoping to MTK

- src/network_analysis.jl
did not realize you couldn't have spaces between docstrings and functions
> fix docstrings

- HISTORY.md
- docs/src/faqs.md
- docs/src/model_creation/dsl_advanced.md
Some starting docs for it. Might be a better spot than where I put it (end of the "[Explicit specification of network species and parameters](https://docs.sciml.ai/Catalyst/stable/model_creation/dsl_advanced/#dsl_advanced_options_declaring_species_and_parameters)" heading)
> `@require_declaration` docs

- docs/src/faqs.md
- docs/src/model_creation/dsl_advanced.md
some adjustments to the docs incorporating Torkel's feedback
> `@require_declaration` docs edits

- src/spatial_reaction_systems/lattice_reaction_systems.jl
- test/spatial_modelling/lattice_reaction_systems.jl
Detecting hierarchical models is different now, so needed to update how this is checked. Since these now are flattened, _in principle_ it should work for spatial modelling. However, we really haven't tested it, so nothing I recommend. Still, I changed it to a warning for the new version.
> Update spatial models for new MTK release

- Project.toml
- ext/CatalystGraphMakieExtension.jl
- ext/CatalystGraphMakieExtension/rn_graph_plot.jl
- test/extensions/graphmakie.jl
Using `Stress()` by default (if connected) to reduce edge crossings, adding support for kwargs, refactoring some code. Graph comparison below (after/before)
> Improvements to graph plotting

- test/runtests.jl
- test/spatial_modelling/lattice_reaction_systems.jl
Should have done this previously, but seems I missed it...
> Reenable spatial tests

- src/spatial_reaction_systems/lattice_reaction_systems.jl
- test/spatial_modelling/lattice_reaction_systems.jl
Long-term we should probably support it. However, doing so will be a decent chunk of work, and rather low priority right now.
> Add errors for array species/parameters when submitted to `LatticeReactionSystem`s

- src/chemistry_functionality.jl
- test/miscellaneous_tests/compound_macro.jl
Fixes the compound issues in https://github.com/SciML/Catalyst.jl/issues/1151
> Compound fixe

- src/reactionsystem_conversions.jl
- src/spatial_reaction_systems/lattice_reaction_systems.jl
- src/spatial_reaction_systems/lattice_sim_struct_interfacing.jl
- test/extensions/lattice_simulation_plotting.jl
Was going to finish this one off https://github.com/SciML/Catalyst.jl/issues/1096, but @vyudu already did. Did the one case remaining in a docstring though. Also, there is this from the `JumpInputs` docstring:
```julia
using Catalyst, OrdinaryDiffEq, JumpProcesses, Plots
k*(1 + sin(t)), 0 --> A
end
jinput = JumpInputs(rn, [:A => 0], (0.0, 10.0), [:k => .5])
@assert jinput.prob isa ODEProblem
jprob = JumpProblem(jinput)
sol = solve(jprob, Tsit5())
plot(sol, idxs = :A)
k, 0 --> A
end
jinput = JumpInputs(rn, [:A => 0], (0.0, 10.0), [:k => .5])
@assert jinput.prob isa DiscreteProblem
jprob = JumpProblem(jinput)
sol = solve(jprob)
plot(sol, idxs = :A)
```
Could this be changed from `OrdinaryDiffEq` to `OrdinaryDiffEqTsit5` @isaacsas?
> Remove last OrdinaryDiffEq mention

- test/reactionsystem_core/reactionsystem.jl
I have added an edge cases to test ReactionSystem which were not tested before.
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.
> test: added an edge case in ReactionSystem

- docs/src/index.md
- src/network_analysis.jl
- test/network_analysis/crn_theory.jl
- Rename `ratematrix` to `adjacencymat`, change its implementation to be more similar to the new API matrix functions in #1134 
- Use the new network analysis API functions in the `iscomplexbalanced`
> network_analysis cleanup: Updating `ratematrix` to be more similar to new matrix API functions

- HISTORY.md
- src/Catalyst.jl
- src/dsl.jl
- src/spatial_reaction_systems/spatial_reactions.jl
- test/dsl/dsl_basic_model_construction.jl
Currently this:
```julia
@reaction_network begin
(p,d), Ø <--> X
end
```
is interpreted as transformation between species Ø and X, as the unicode for the letter Ø is used instead of the empty set ∅.
> Consider the Danish/Norwegian letter ∅ as the empty set symbol (Ø)

- Project.toml
- docs/src/model_creation/model_visualisation.md
- ext/CatalystGraphMakieExtension.jl
- ext/CatalystGraphMakieExtension/rn_graph_plot.jl
> Fix graph defaults, plotting graphs

- src/dsl.jl
- test/reactionsystem_core/custom_crn_functions.jl
Follow-up to https://github.com/SciML/Catalyst.jl/pull/985. Builds on https://github.com/SciML/Catalyst.jl/pull/1192 (for tests to pass.
Basically does the reordering of the functions in the DSL file (which was not part of the original PR to make it less messy). With one exception (flipping the order of the `get_psexpr` and `get_usexpr` functions, to have the order with which they appear in the file), all changes are to reorder the option handling functions to appear in the same order in which they were called in the main function.
Also slightly renames two of these option handling functions, so that their names correspond to the option the handle.
> Finish dsl src update (reorder functions)

- README.md
@TorkelE I think we should add some installation instructions in the README that tell people not to install ModelingToolkit versions post 9.59.
> Update README.md with installation instructions

- docs/src/model_creation/examples/basic_CRN_library.md
Should solve https://github.com/SciML/Catalyst.jl/issues/1105
Right now I just add a simple example for the CRN library example. If we are happy with text and approach we can copy across all (or some?) of the doc pages.
This is how it looks like by default:
And this when you click to expand the menu
> Add tutorial set-up code

- test/simulation_and_solving/jacobian_construction.jl
- test/test_functions.jl
After the latest test failures in the spatial tests I checked and realised that we don't actually properly test whether the generated sparse Jacobians are correct. I guess, ironically, a lot of the core feature tests were written way back in time before when we made more assumptions of upstream correctness (and our own, I guess, still think the early tests were quite good though). Hence a lot of stuff is actually caught in extensions/niche feature tests that are actually testing other stuff.
I haven't actually isolated the latest problems, so not sure if they are from Catalyst or somewhere else (or even if they are a problem). However, we get failures here as well, so not related to the spatial stuff that is actually failing. I also only get failures of these tests on the latest version, …
> Add additional Jacobian tests (including sparsity)

- src/spatial_reaction_systems/spatial_reactions.jl
- test/compositional_modelling/component_based_model_creation.jl
- test/reactionsystem_core/reactionsystem.jl
- test/runtests.jl
- test/simulation_and_solving/jacobian_construction.jl
- test/simulation_and_solving/simulate_ODEs.jl
- test/simulation_and_solving/simulate_SDEs.jl
- test/test_functions.jl
[contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
[COLPRAC](https://github.com/SciML/COLPRAC).
Add any other context about the problem here.
> test: fix `DelayParentScope` test

- src/reactionsystem_serialisation/serialise_reactionsystem.jl
- test/miscellaneous_tests/reactionsystem_serialisation.jl
If the `annotate = true` (default) option is used, a string like 
```julia
```
will be added to the beginning of the file, telling which version of Catalyst the model was serialised with.
> Add catalys version to serialisation function

- docs/src/steady_state_functionality/nonlinear_solve.md
> Remove `remove_conserved` warning from nonlinear solve doc page

- docs/src/model_creation/functional_parameters.md
- src/dsl.jl
- test/reactionsystem_core/functional_parameters.jl
Solves: https://github.com/SciML/Catalyst.jl/issues/1208
The fix was easy, just a minor detail in how we parsed function which throw an error for this case.
> Enables DSL interpolation of a function name only

- src/chemistry_functionality.jl
- src/dsl.jl
- src/expression_utils.jl
With v15 aboud to be released I started deleting all my related local branches. Had one I started regarding some observables fix which, while never pushed, did include a big improvement to one of the expression parsing functions (shorter, easier to read, and can extract `[1:2]` from `X(t)[1:2]` expressions, if we ever need it).
Was a shame to just throw it away so figured I'd removed the other stuff and PR it.
has no actual effect on Catalyst. can be merged whenever we feel like it.
> Improve expression parser function

- test/simulation_and_solving/hybrid_models.jl
Hopefully this fixes the timeout for the prerelease hybrid tests.
@ChrisRackauckas should doing stuff like `some_vector .+= sol(times; idxs = :X)` causing the following message:
```julia
┌ Warning: `Base.getindex(A::AbstractDiffEqArray, i::Int)` is deprecated, use `Base.getindex(A, :, i)` instead.
│   caller = _broadcast_getindex at broadcast.jl:652 [inlined]
```
It seems like this is something that should work?
> Fix indexing deprecation warning

- test/simulation_and_solving/hybrid_models.jl
Increased the timespan of one test. Previously it could actually fail very occasionally. The test is still fast (<1 second). Have run it 10000 times, still no failure.
> Fix ocasional hybrid test failure

- test/reactionsystem_core/events.jl
- test/reactionsystem_core/higher_order_reactions.jl
- test/reactionsystem_core/parameter_type_designation.jl
- test/reactionsystem_core/reactionsystem.jl
- test/reactionsystem_core/symbolic_stoichiometry.jl
- test/simulation_and_solving/simulate_jumps.jl
- test/upstream/mtk_problem_inputs.jl
- test/upstream/mtk_structure_indexing.jl
Mostly moves to using the `JumpInputs` interface throughout the tests. Should remove most warnings in the tests.
> Remove` DiscreteProblem`s in tests
